# nonk8s
apiVersion: "backstage.io/v1alpha1"
kind: "Component"
metadata:
  name: "matrikkel-actions"
  tags:
  - "public"
spec:
  type: "ops"
  lifecycle: "production"
  owner: "heimdall"
  system: "m22"
