name: Apps repo deploy
description: Updates apps-repo to deploy changes
inputs:
  apps:
    description: Comma separated list of apps to deploy (cluster:namespace:app:version)
    required: true
  dryrun:
    description: Should run be a dryrun, and not commit any changes. (true/false)
    required: false
    default: "false"

runs:
  using: composite
  steps:
    - uses: octo-sts/action@v1.0.1
      id: octo-sts
      with:
        scope: kartverket/heimdall-apps
        identity: heimdall
    - name: Checkout the repository
      uses: actions/checkout@v4
      with:
        repository: kartverket/heimdall-apps
        ref: main
        token: ${{ steps.octo-sts.outputs.token }}
        fetch-depth: 0
    - name: Setup Bun
      uses: oven-sh/setup-bun@v2
    - name: Update versions
      shell: bash
      run: |
        set -euo pipefail
        cd "${{ github.action_path }}"
        bun install --frozen-lockfile
        bun run src/index.ts
      env:
        INPUT_APPS: ${{ inputs.apps }}
        INPUT_DRYRUN: ${{ inputs.dryrun }}
