name: Test worflow

on:
  workflow_dispatch:
    inputs:
      replicas:
        description: "Number of replicas"
        required: true
        type: number

permissions:
  id-token: write
  contents: write
  pull-requests: write

jobs:
  create_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Update replicas & commit
        run: |
          # New branch - update-replicas-[new replica num]-[date in UTC]
          BRANCH_NAME="update-replicas-${{ inputs.replicas }}-$(date --utc '+%Y-%m-%d-%H-%M-%SZ')"
          git switch -c "$BRANCH_NAME"
          # Update replicas
          echo '${{ inputs.replicas }}' >> src/replicas
          git add src/replicas

          git status # DEBUG
          echo '${{ toJson(github.event.sender) }}' # DEBUG

          # Get name of person triggering the workflow, and add commiter as '[action] Georg Maskot'
          USERNAME='${{ github.event.sender.login }}'
          NAME="$(gh api "users/$USERNAME" --jq '.name')"
          git config --global user.name "[action] $NAME"
          git config --global user.email "$USERNAME@users.noreply.github.com"
          MESSAGE='[action] Scale replicas to ${{ inputs.replicas }}'
          git commit -m "$MESSAGE"
          git show # DEBUG
          git remote -v # DEBUG

          # gh pr create can push for us, but we want to explicity avoid interactive behavior by pushing first and using --head
          git push --set-upstream origin "$BRANCH_NAME"
          gh pr create --title "[automerge]$MESSAGE" --body "Action triggered by @$USERNAME" --head "$BRANCH_NAME"
          gh pr merge --auto --rebase
        env:
          GH_TOKEN: ${{ github.token }}
          
