name: Test worflow

on:
  workflow_dispatch:
    inputs:
      replicas:
        description: "Number of replicas"
        required: true
        type: number

permissions:
  id-token: write
  contents: write

jobs:
  create_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Update replicas & commit
        run: |
          # Update replicas
          echo '${{ inputs.replicas }}' >> src/replicas
          git add src/replicas

          git status # DEBUG
          echo '${{ toJson(github.event.sender) }}' # DEBUG

          # Get name of person triggering the workflow, and add commiter as '[action] Georg Maskot'
          NAME="$(gh api 'users/${{ github.event.sender.login }}' --jq '.name')"
          git config --global user.name "[action] $NAME"
          git config --global user.email '${{ github.event.sender.login }}@users.noreply.github.com'
          git commit -m '[action] Scale replicas to ${{ inputs.replicas }}'
          git show # DEBUG
          git push
        env:
          GH_TOKEN: ${{ github.token }}
          
